[package]
authors = ["Ricky Han <tectonic@rickyhan.com>"]
category = "Database"
description = "fast datastore server for contiguous order book ticks"
exclude = ["db/*", "test/test-data/*"]
keywords = ["finance", "datastore", "database", "financial"]
license = "MIT"
name = "tectonicdb"
readme = "README.md"
version = "0.2.1"

[[bin]]
name = "tectonic-server"
path = "src/bin/server/main.rs"

[[bin]]
name = "tectonic-cli"
path = "src/bin/cli/main.rs"

[[bin]]
name = "dtfsplit"
path = "src/bin/dtfsplit/main.rs"
publish = true

[[bin]]
name = "dtfcat"
path = "src/bin/dtfcat/main.rs"
publish = true

[[bin]]
name = "dtfconcat"
path = "src/bin/dtfconcat/main.rs"
publish = true

[dependencies]
bitflags = "1.0.0"
byteorder = "1.1.0"
chrono = "0.4"
circular-queue = "0.2.0"
clap = "~2.26"
config = "0.6"
csv = "1.0.0-beta.5"
fern = "0.5"
futures = "0.1.14"
log = "0.4"
openssl-probe = "0.1.2"
reqwest = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1.38"
tokio-core = "0.1"
tokio-io = "0.1"

[dependencies.notify]
optional = true
version = "4.0.0"

[dependencies.uuid]
features = ["serde"]
version = "0.5.1"

[features]
default = ["gcs"]
gcs = ["notify"]

[lib]
crate-type = ["cdylib", "dylib", "rlib"]
name = "libtectonic"
path = "src/lib/lib.rs"
repository = "https://github.com/rickyhan/tectonicdb"
version = "0.2.0"
